# Generated by Django 3.1.1 on 2020-11-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
