# Generated by Django 3.1.1 on 2020-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehub', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productcategory',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
