# Generated by Django 3.0.5 on 2020-11-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehub', '0004_productpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productpage',
            new_name='fashion',
        ),
    ]
